import React from 'react';
import { Handshake, UserCheck, Settings, Cpu, ShieldAlert, CreditCard, Laptop, Ban, Info, Scale } from 'lucide-react';
import PolicyPageLayout from '../web-components/PolicyPageLayout';

const VendorAgreement = () => {
  const seoKeywords = [
    "Vendor agreement template",
    "Multi-business commerce platform",
    "Vendor management software agreement",
    "SaaS platform vendor terms",
    "Online ordering vendor policy",
    "White-label business platform agreement",
    "Business onboarding agreement India"
  ];

  const sections = [
    {
      id: "agreement-intro",
      title: "Agreement Overview",
      icon: <Info className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <p>
            This Vendor Agreement (“Agreement”) is entered into between Mobrand and the registered business or merchant (“Vendor”) using the Mobrand platform, dashboards, and client applications.
          </p>
          <p>
            By registering as a vendor or business partner on Mobrand, you agree to comply with and be bound by all terms, guidelines, and pricing schedules contained herein.
          </p>
          <p>
            Mobrand is an all-in-one multi-business commerce platform that enables businesses to manage products, services, orders, customers, and online operations through websites, mobile applications, and vendor dashboards.
          </p>
        </div>
      )
    },
    {
      id: "vendor-eligibility",
      title: "Vendor Eligibility",
      icon: <UserCheck className="w-5 h-5" />,
      content: (
        <div className="space-y-3">
          <p>To register and maintain an active Vendor account on Mobrand:</p>
          <ul className="space-y-2 list-disc list-inside pl-2 text-sm">
            <li>You must hold all active government licenses, permits, and tax registrations required to operate your business.</li>
            <li>You must provide verified, accurate, and current business details (e.g., GST details, PAN card, store address).</li>
            <li>You must be legally authorized to sign contracts on behalf of the registered business entity.</li>
          </ul>
          <p>Mobrand reserves the final right to approve or reject vendor registrations at its sole discretion.</p>
        </div>
      )
    },
    {
      id: "vendor-responsibilities",
      title: "Vendor Responsibilities",
      icon: <Settings className="w-5 h-5" />,
      content: (
        <div className="space-y-3">
          <p>As an active Vendor using the Mobrand platform, you are solely responsible for:</p>
          <ul className="space-y-2 list-disc list-inside pl-2 text-sm">
            <li>Providing and maintaining accurate business hours, store images, addresses, and details.</li>
            <li>Uploading and updating correct product catalogues, menus, pricing, description, and real-time inventory levels.</li>
            <li>Promptly processing and fulfilling customer orders in a professional, timely manner.</li>
            <li>The merchantable quality, safety, legality, and accuracy of the goods or services provided.</li>
            <li>Maintaining customer communication and handling grievances related to product quality.</li>
          </ul>
        </div>
      )
    },
    {
      id: "platform-usage",
      title: "Platform Usage",
      icon: <Cpu className="w-5 h-5" />,
      content: (
        <p>
          Vendors are granted a non-exclusive, non-transferable, revocable license to access the Mobrand software to manage inventory, catalog products/services, track sales, download business analytics reports, and communicate with customers. Mobrand reserves the right to improve, upgrade, modify, or deprecate platform features at any time.
        </p>
      )
    },
    {
      id: "subscription-fees",
      title: "Subscription & Fees",
      icon: <CreditCard className="w-5 h-5" />,
      content: (
        <div className="space-y-3">
          <p>Vendors agree to pay all applicable setup fees, recurring subscription fees, and premium integration charges as outlined in their selected plan.</p>
          <ul className="space-y-2 list-disc list-inside pl-2 text-sm">
            <li>All fees must be cleared on time to avoid disruption of digital storefronts.</li>
            <li>Non-payment of subscription fees will result in automatic storefront suspension.</li>
            <li>Fees are exclusive of applicable taxes unless stated otherwise.</li>
          </ul>
        </div>
      )
    },
    {
      id: "payments-transactions",
      title: "Payments & Transactions",
      icon: <CreditCard className="w-5 h-5" />,
      content: (
        <p>
          Payment processing and digital wallet settlement are handled securely by integrated third-party payment gateways. The transaction records generated by Mobrand shall be considered valid evidence in any settlement. Mobrand is not responsible for settlement delays caused by third-party banking errors or merchant gateway outages.
        </p>
      )
    },
    {
      id: "whitelabel-services",
      title: "White-Label Services",
      icon: <Laptop className="w-5 h-5" />,
      content: (
        <p>
          Premium plan vendors may request customized white-label mobile applications publishing on App Stores under their own brand. Setup and customization fees are charged separately. Brand assets, logos, and custom graphics must be provided in high resolution.
        </p>
      )
    },
    {
      id: "prohibited-activities",
      title: "Prohibited Activities",
      icon: <Ban className="w-5 h-5" />,
      content: (
        <div className="space-y-3">
          <p>Vendors may not:</p>
          <ul className="space-y-2 list-disc list-inside pl-2 text-sm text-slate-600">
            <li>Sell, offer, or promote contraband, illegal substances, or counterfeit items.</li>
            <li>Upload misleading pricing, inaccurate weight information, or false descriptions.</li>
            <li>Engage in duplicate billing or bait-and-switch ordering schemes.</li>
            <li>Scrape or misappropriate platform data, customer contacts, or competitor information.</li>
          </ul>
        </div>
      )
    },
    {
      id: "suspension-termination",
      title: "Suspension & Termination",
      icon: <ShieldAlert className="w-5 h-5" />,
      content: (
        <p>
          Mobrand reserves the absolute right to suspend or terminate any Vendor account instantly, without prior notice, in the event of fraud, policy violations, consumer complaints, non-payment of subscription dues, or illegal business conduct. Suspended accounts are ineligible for refunds.
        </p>
      )
    },
    {
      id: "liability-limitation",
      title: "Limitation of Liability",
      icon: <Scale className="w-5 h-5" />,
      content: (
        <p>
          Mobrand operates strictly as a technology SaaS provider connecting vendors with customers. We are not responsible for delivery failures, product damages, merchant losses, regulatory non-compliance of products, or third-party logistic mishaps.
        </p>
      )
    }
  ];

  return (
    <PolicyPageLayout
      title="Vendor Agreement"
      subtitle="Standard contract and platform guidelines for merchants and business owners"
      effectiveDate="May 8, 2026"
      sections={sections}
      seoKeywords={seoKeywords}
    />
  );
};

export default VendorAgreement;
